# Generated by Django 4.2.30 on 2026-04-27 17:02

import backend.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('A', 'Apartment'), ('P', 'Penthouse'), ('V', 'Villa')], default='A', max_length=200)),
                ('room', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occupancy', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('breakfast', models.BooleanField(default=True)),
                ('breakfast_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created published')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created published')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(default=datetime.date.today)),
                ('check_in_timestamp', models.CharField(max_length=200)),
                ('check_out', models.DateField(default=backend.models.Booking.default_check_out)),
                ('check_out_timestamp', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=backend.models.Booking.duration_calculator, validators=[django.core.validators.MinValueValidator(1)])),
                ('email', models.EmailField(max_length=254)),
                ('origin', models.CharField(max_length=200)),
                ('guests', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('breakfast', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.unit')),
            ],
        ),
    ]
