# Generated by Django 4.2.30 on 2026-04-27 17:35

import backend.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_unit_occupancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='room',
        ),
        migrations.AddField(
            model_name='unit',
            name='number_of_bathrooms',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='unit',
            name='number_of_rooms',
            field=models.IntegerField(default=backend.models.Unit.number_of_rooms_in_unit, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
