# Generated by Django 4.2.30 on 2026-04-27 18:46

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_available_unit_active_remove_booking_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='email',
            new_name='guest_email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='guests_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_in_timestamp',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_timestamp',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='origin',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(default=backend.models.Booking.default_time),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(default=backend.models.Booking.default_time),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_origin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
