# Generated by Django 4.2.30 on 2026-04-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_email_booking_guest_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='total',
        ),
    ]
