# Generated by Django 4.2.30 on 2026-04-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_price_booking_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Penthouse', 'Penthouse'), ('Villa', 'Villa')], default='A', max_length=200),
        ),
    ]
