apiVersion: v1
kind: Service
metadata:
  name: {{ include "game-2048.fullname" . }}
  namespace: {{ .Values.namespace | default "game" }}
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-type: external
    # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    # service.beta.kubernetes.io/aws-load-balancer-scheme: {{ .Values.service.scheme | default "internal" }}
    # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  labels:
    {{- include "game-2048.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "game-2048.selectorLabels" . | nindent 4 }}
