apiVersion: 1
groups:
    - orgId: 1
      name: 1m Mark
      folder: Host
      interval: 1m
      rules:
        - uid: afn2n8dcac268a
          title: CPU Overload
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 21600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: 1 - avg(rate(system_cpu_time_seconds_total{k8s_node_name="",state="idle"}[$__rate_interval]))
                instant: true
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: DJANGO_HOST
          panelId: 1
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: DJANGO_HOST
            __panelId__: "1"
            summary: CPU Overload
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Alert Manager
