name: Terraform Plan
run-name: ${{ github.actor }} is planning the Stratoshpere 🚀
on: [push]
jobs:
  Terraform-Plan:
    runs-on: ubuntu-24.04
    steps:
      - name: Testing environment prep
        run: |
          echo 'Starting env prep for testing...'
          apt update && apt install -y gnupg software-properties-common curl wget unzip
      - name: Terraform - Installation
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
          apt update && apt install terraform -y
          terraform --version
      - name: AWS CLI - Installation
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          aws --version
      - name: AWS CLI - Configuration
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile terraform
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile terraform
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: VPC - TF Plan
        run: |
          cd ${{ github.workspace }}/infrastructure/vpc
          terraform init
          terraform plan
          aws configure set aws_access_key_id '' --profile terraform
          aws configure set aws_secret_access_key '' --profile terraform
